frr version 10.0.1
frr defaults traditional
hostname r13
!
interface lo
 ip address 10.255.0.13/32
 ip router isis 1
 isis passive
!
interface eth1
 ip address 10.0.0.3/31
 ip router isis 1
 isis network point-to-point
!
interface eth2
 ip address 10.0.0.4/31
 ip router isis 1
 isis network point-to-point
!
!
router isis 1
 net 49.0001.0102.5500.0013.00
 is-type level-2-only
!
router bgp 65001
 bgp router-id 10.255.0.13
 no bgp ebgp-requires-policy
 neighbor 10.255.0.11 remote-as 65001
 neighbor 10.255.0.11 update-source lo
 neighbor 10.255.0.12 remote-as 65001
 neighbor 10.255.0.12 update-source lo
!
