frr version 10.0.1
frr defaults traditional
hostname r31
!
interface lo
 ip address 10.255.0.31/32

!

interface eth1
 ip address 10.0.0.13/31

!

interface eth2
 ip address 10.10.2.1/24

!




ip prefix-list ALLOWED_PREFIXES permit 10.10.0.0/16 le 24

!

router bgp 65003
 bgp router-id 10.255.0.31
 no bgp ebgp-requires-policy


 network 10.10.2.0/24




 ! eBGP

 neighbor 10.0.0.12 remote-as 65001
 neighbor 10.0.0.12 route-map RM_IN_10.0.0.12 in
 neighbor 10.0.0.12 route-map RM_OUT_10.0.0.12 out
 neighbor 10.0.0.12 maximum-prefix 100


!


route-map RM_IN_10.0.0.12 permit 10
 match ip address prefix-list ALLOWED_PREFIXES
 set local-preference 150
!
route-map RM_OUT_10.0.0.12 permit 10
 match ip address prefix-list ALLOWED_PREFIXES
 set community 65003:1
!

