frr version 10.0.1
frr defaults traditional
hostname r12
!
interface lo
 ip address 10.255.0.12/32
 ip router isis 1
 isis passive
!
interface eth1
 ip address 10.0.0.1/31
 ip router isis 1
 isis network point-to-point
!
interface eth2
 ip address 10.0.0.2/31
 ip router isis 1
 isis network point-to-point
!
interface eth3
 ip address 10.0.0.10/31
!
router isis 1
 net 49.0001.0102.5500.0012.00
 is-type level-2-only
!
ip prefix-list ALLOWED_PREFIXES permit 10.10.0.0/16 le 24
!
router bgp 65001
 bgp router-id 10.255.0.12
 neighbor 10.255.0.11 remote-as 65001
 neighbor 10.255.0.11 update-source lo
 neighbor 10.255.0.13 remote-as 65001
 neighbor 10.255.0.13 update-source lo
 neighbor 10.0.0.8 remote-as 65001
 neighbor 10.0.0.8 maximum-prefix 100
 neighbor 10.0.0.8 route-map RM_IN_10.0.0.8 in
 neighbor 10.0.0.8 route-map RM_OUT_10.0.0.8 out
 neighbor 10.0.0.11 remote-as 65002
 neighbor 10.0.0.11 maximum-prefix 100
 neighbor 10.0.0.11 route-map RM_IN_10.0.0.11 in
 neighbor 10.0.0.11 route-map RM_OUT_10.0.0.11 out
 neighbor 10.0.0.12 remote-as 65001
 neighbor 10.0.0.12 maximum-prefix 100
 neighbor 10.0.0.12 route-map RM_IN_10.0.0.12 in
 neighbor 10.0.0.12 route-map RM_OUT_10.0.0.12 out
!
route-map RM_IN_10.0.0.11 permit 10
 match ip address prefix-list ALLOWED_PREFIXES
 set local-preference 100
!
route-map RM_OUT_10.0.0.11 permit 10
 match ip address prefix-list ALLOWED_PREFIXES
 set community 65001:1
!
