frr version 10.0.1
frr defaults traditional
hostname r11
!
interface lo
 ip address 10.255.0.11/32

 ip router isis 1
 isis passive

!

interface eth1
 ip address 10.0.0.0/31

 ip router isis 1
 isis network point-to-point

!

interface eth2
 ip address 10.0.0.5/31

 ip router isis 1
 isis network point-to-point

!

interface eth3
 ip address 10.0.0.8/31

!

interface eth4
 ip address 10.10.1.1/24

!


router isis 1
 net 49.0001.0102.5500.0011.00
 is-type level-2-only
!



ip prefix-list ALLOWED_PREFIXES permit 10.10.0.0/16 le 24

!

router bgp 65001
 bgp router-id 10.255.0.11
 no bgp ebgp-requires-policy


 network 10.10.1.0/24



 ! iBGP

 neighbor 10.255.0.12 remote-as 65001
 neighbor 10.255.0.12 update-source lo

 neighbor 10.255.0.13 remote-as 65001
 neighbor 10.255.0.13 update-source lo



 ! eBGP

 neighbor 10.0.0.9 remote-as 65002
 neighbor 10.0.0.9 route-map RM_IN_10.0.0.9 in
 neighbor 10.0.0.9 route-map RM_OUT_10.0.0.9 out
 neighbor 10.0.0.9 maximum-prefix 100


!


route-map RM_IN_10.0.0.9 permit 10
 match ip address prefix-list ALLOWED_PREFIXES
 set local-preference 200
!
route-map RM_OUT_10.0.0.9 permit 10
 match ip address prefix-list ALLOWED_PREFIXES
 set community 65001:1
!

